name: Auto Deploy Node DevOps Dashboard to EC2

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Latest Repository Code
        uses: actions/checkout@v4

      - name: Setup SSH Private Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/nodeappkp.pem
          chmod 600 ~/.ssh/nodeappkp.pem

      - name: Deploy Application to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/nodeappkp.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

            echo "Connected to EC2..."

            cd /var/www/Node-app

            echo "Pulling latest code from GitHub..."
            git pull origin main

            echo "Installing backend dependencies..."
            cd backend
            npm install

            echo "Installing frontend dependencies..."
            cd ../frontend
            rm -rf node_modules
            rm -f package-lock.json
            npm cache clean --force
            npm install
            npm run build

            echo "Restarting PM2 backend..."
            cd ../backend
            pm2 restart devops-dashboard || pm2 start ecosystem.config.js
            pm2 save

            echo "Deployment Finished Successfully."

          EOF
